#!/bin/sh

code --install-extension ms-vscode.atom-keybindings
code --install-extension formulahendry.auto-close-tag
code --install-extension formulahendry.auto-rename-tag
code --install-extension aaron-bond.better-comments
code --install-extension naumovs.color-highlight
code --install-extension mikestead.dotenv
code --install-extension editorconfig.editorconfig
code --install-extension dbaeumer.vscode-eslint
code --install-extension codezombiech.gitignore
code --install-extension abusaidm.html-snippets
code --install-extension xabikos.javascriptsnippets
code --install-extension eriklynd.json-tools
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension yzhang.markdown-all-in-one
code --install-extension eg2.vscode-npm-script
code --install-extension christian-kohler.npm-intellisense
code --install-extension zhuangtongfa.material-theme
code --install-extension christian-kohler.path-intellisense
code --install-extension alefragnani.project-manager
code --install-extension richie5um2.vscode-sort-json
code --install-extension tyriar.sort-lines
code --install-extension cssho.vscode-svgviewer
code --install-extension gruntfuggly.todo-tree
code --install-extension deerawan.vscode-faker
code --install-extension vscode-icons-team.vscode-icons
code --install-extension wakatime.vscode-wakatime
code --install-extension michelemelluso.code-beautifier
code --install-extension dlasagno.wal-theme
